<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <NoWarn>CA1515</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnTopic.All\OnTopic.All.csproj" />
    <ProjectReference Include="..\OnTopic.ViewModels\OnTopic.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>