// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Handled by Requires()", Scope = "member", Target = "~M:Ignia.Topics.AspNetCore.Mvc.TopicViewLocationExpander.ExpandViewLocations(Microsoft.AspNetCore.Mvc.Razor.ViewLocationExpanderContext,System.Collections.Generic.IEnumerable{System.String})~System.Collections.Generic.IEnumerable{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Handled by Requires()", Scope = "member", Target = "~M:Ignia.Topics.AspNetCore.Mvc.ServiceCollectionExtensions.AddTopicSupport(Microsoft.Extensions.DependencyInjection.IMvcBuilder)~Microsoft.Extensions.DependencyInjection.IMvcBuilder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Handled by Requires()", Scope = "member", Target = "~M:Ignia.Topics.AspNetCore.Mvc.TopicViewResult.ExecuteResultAsync(Microsoft.AspNetCore.Mvc.ActionContext)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Handled by Requires()", Scope = "member", Target = "~M:Ignia.Topics.AspNetCore.Mvc.TopicViewResultExecutor.ExecuteAsync(Microsoft.AspNetCore.Mvc.ActionContext,Ignia.Topics.AspNetCore.Mvc.TopicViewResult)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Handled by Requires()", Scope = "member", Target = "~M:Ignia.Topics.AspNetCore.Mvc.TopicViewResultExecutor.FindView(Microsoft.AspNetCore.Mvc.ActionContext,Ignia.Topics.AspNetCore.Mvc.TopicViewResult)~Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Handled by Requires()", Scope = "member", Target = "~M:Ignia.Topics.AspNetCore.Mvc.TopicViewLocationExpander.PopulateValues(Microsoft.AspNetCore.Mvc.Razor.ViewLocationExpanderContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Handled by Requires()", Scope = "member", Target = "~M:Ignia.Topics.AspNetCore.Mvc.Controllers.TopicController.OnActionExecuting(Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext)")]
